# Generated by Django 5.0.7 on 2024-11-28 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_camera_feed_url_area_video_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='is_suspected',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='reason_suspected',
        ),
        migrations.CreateModel(
            name='SuspectVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_suspected', models.TextField()),
                ('crime_committed', models.CharField(max_length=255)),
                ('crime_details', models.TextField(blank=True, null=True)),
                ('reported_date', models.DateField(auto_now_add=True)),
                ('police_station', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_suspects', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suspect_details', to='core.vehicle')),
            ],
        ),
    ]
