# Generated by Django 5.0.7 on 2024-12-07 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_vehicle_is_suspected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, unique=True)),
                ('classification', models.CharField(choices=[('Suspect', 'Suspect'), ('Not Suspect', 'Not Suspect'), ('Unknown', 'Unknown')], max_length=20)),
                ('area_id', models.IntegerField()),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicle')),
            ],
        ),
    ]
