# Generated by Django 5.0.7 on 2025-04-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_detectedplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedplate',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
